# Generated by Django 4.2.4 on 2023-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dump", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liveassetprice",
            old_name="asset_price",
            new_name="copper_price",
        ),
        migrations.RemoveField(
            model_name="liveassetprice",
            name="asset_name",
        ),
        migrations.AddField(
            model_name="liveassetprice",
            name="gas_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liveassetprice",
            name="gold_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liveassetprice",
            name="oil_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liveassetprice",
            name="platinum_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liveassetprice",
            name="silver_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
